-- MySQL Script generated by MySQL Workbench
-- Mon Apr 25 13:26:51 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema creepy_blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema creepy_blog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `creepy_blog` DEFAULT CHARACTER SET utf8 ;
USE `creepy_blog` ;


-- -----------------------------------------------------
-- Table `creepy_blog`.`cb_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creepy_blog`.`cb_role` (
  `id` INT UNSIGNED NOT NULL,
  `role_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creepy_blog`.`cb_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creepy_blog`.`cb_user` (
  `id` INT UNSIGNED NOT NULL,
  `firstname` VARCHAR(150) NULL,
  `lastname` VARCHAR(150) NULL,
  `pseudo` VARCHAR(150) NULL,
  `email` VARCHAR(200) NULL,
  `role_fk` INT NULL,
  `cb_role_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cb_user_cb_role1_idx` (`cb_role_id` ASC) VISIBLE,
  CONSTRAINT `fk_cb_user_cb_role1`
    FOREIGN KEY (`cb_role_id`)
    REFERENCES `creepy_blog`.`cb_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creepy_blog`.`cb_article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creepy_blog`.`cb_article` (
  `id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(45) NULL,
  `content` TEXT NULL,
  `user_fk` INT UNSIGNED NOT NULL,
  `comment_fk` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `article_user_idx` (`user_fk` ASC) VISIBLE,
  CONSTRAINT `article_user`
    FOREIGN KEY (`user_fk`)
    REFERENCES `creepy_blog`.`cb_user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creepy_blog`.`cb_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creepy_blog`.`cb_comment` (
  `content` TEXT NULL,
  `user_fk` INT NULL,
  `article_fk` INT NULL,
  `cb_user_id` INT UNSIGNED NOT NULL,
  UNIQUE INDEX `user_fk_UNIQUE` (`user_fk` ASC) VISIBLE,
  UNIQUE INDEX `article_fk_UNIQUE` (`article_fk` ASC) VISIBLE,
  INDEX `fk_cb_comment_cb_user1_idx` (`cb_user_id` ASC) VISIBLE,
  CONSTRAINT `comment_article`
    FOREIGN KEY ()
    REFERENCES `creepy_blog`.`cb_article` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cb_comment_cb_user1`
    FOREIGN KEY (`cb_user_id`)
    REFERENCES `creepy_blog`.`cb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
